### ISSUE TITLE
[w2-pandas-project] Olaya Marqués Gómez

### ISSUE THREAD

**Issue by olaya-marques** [Ironhack-Data-Madrid-Mayo-2021/w2-pandas-project#1]
Este es el enlace al repositorio que contiene el Proyecto 1. Buena tarde :)
https://github.com/olaya-marques/p1-shark-attack.git

**Comment by sheriffff** [comment]
Olaya, brutal trabajo de investigación y vaya cacho de report!!
 - Quizás el README.md lo haría un poco más cortito, y pondría un link a una presentación que contenga todo el detalle de resultados.
 - Buena hipótesis y muy buenas gráficas para sacar conclusiones.
 - Vete pasando al inglés, lo agradecerás en el futuro!
 - Buena estructura de archivos y de notebooks. Hecho de menos más funciones en el archivo `Funciones.py` que se vean llamadas por los diferentes notebooks.
 - Muy bien que añadas bibliografía.
 - Muy bien, celdas de markdown para comentarios y títulos en los notebooks.
 - En vez de esto ```
USA = data4[(data4["Country"] == "USA")]
NUEVA_ZELANDA = data4[(data4["Country"] == "NEW ZEALAND")]
BRASIL = data4[(data4["Country"] == "BRAZIL")]
INDONESIA = data4[(data4["Country"] == "INDONESIA")]
SOUTH_AFRICA = data4[(data4["Country"] == "SOUTH AFRICA")]
IRELAND = data4[(data4["Country"] == "IRELAND")]```
puedes usar algo tipo `data[data4["Country"].isin(tu_lista_de_paises)]`

En general fenomenal.
