### ISSUE TITLE
[w2-pandas-project] - Cristian Castro Blua

### ISSUE THREAD

**Issue by ccastroblua** [Ironhack-Data-Madrid-Mayo-2021/w2-pandas-project#2]
https://github.com/ccastroblua/data-cleaning-pandas

**Comment by olmocorell** [comment]
¡¡Hola Cristian!! 
En primer lugar, perdona por haber tardado en venir a corregir este proyecto...
Te cuento cosas:

- Readme
Enhorabuena, está perfecto. Un readme que invita a seguir leyendo... no pierdas esa estructura de imagen, breve explicación, partes del proyecto y stack de tecnologías.

- Estructura del repo
<img width="791" alt="Captura de pantalla 2021-06-22 a las 16 23 16" src="https://user-images.githubusercontent.com/57899051/122941985-2842cc00-d376-11eb-9b4a-a6eb0c5570ef.png">
Está genial, pero ojo ese csv en la carpeta data

- Eficiencia del código 
Muy bien hecho el archivo de funciones para importarlo. 
¿Cuál es el siguiente nivel? Añadir "docstrings" a las funciones
![dostring](https://user-images.githubusercontent.com/57899051/122944705-55907980-d378-11eb-941b-4775a5b47462.png)
¿Y cómo hacemos eso? Te dejo [este](https://dev.to/highflyer910/what-is-a-python-docstring-44eo) artículo para que eches un vistazo.

- Jupyter de análisis
Gráficos bien elegidos y comentados. Con las fig bien grandotas y buen uso del markdown para comentarlas.

- Jupyter de limpiezaa
En este jupyter también es conveniente que pongas comentarios.  Aunque está espectacular que llames a las funciones de tu archivo de funciones, está bien que lo expliques con comentarios más allá de Second cleaning function o third...
Comentar el código siempre es un win.


¡¡Enhorabuena Cristian!! estás haciendo un buen trabajo y vas camino de pasarte ironhack en nivel pro.
¡¡Sigue así!!


![shark](https://user-images.githubusercontent.com/57899051/122953342-ef5b2500-d37e-11eb-89bd-184afcf9251e.jpeg)
