### ISSUE TITLE
[w2-pandas-project] Alvaro Garcia Blazquez

### ISSUE THREAD

**Issue by alvarogb1919** [Ironhack-Data-Madrid-Mayo-2021/w2-pandas-project#3]
https://github.com/alvarogb1919/data-cleaning-pandas

**Comment by olmocorell** [comment]
¡Hola Álvaro!
Te di feedback en su momento, así que solamente te recuerdo las cosas que te dije ¿vale?
En cuanto al readme:
Cuidado con las rutas de las imágenes que mira cómo se están viendo ahora mismo:
<img width="690" alt="Captura de pantalla 2021-06-22 a las 16 01 01" src="https://user-images.githubusercontent.com/57899051/122938446-0c89f680-d373-11eb-8bb4-4d2cda38d775.png">

Recuerda explicar la estructura del repositorio y mencionar la hipótesis para animar al lector a entrar dentro del código. También añadir al final el stack de tecnologías con los enlaces a la documentación.

Por otra parte, en cuanto al proyecto, lo que te comenté sobre hacer dos limpiezas. Una primera para aproximarnos a los datos y luego otra enfocada en la hipótesis y en los caminos que tenemos que seguir para llegar hasta ella.
Bien el dropna con el uso del how
Por otra parte, el tema de las funciones fuera del jupyter, aunque no era obligatorio, pero tiienes nivel para hacerlo.
Y el tema de enfangarte con la limpieza de la columna "actividades"
Ya hablamos que por cuestiones personales se quedó un poco cojo, pero aún así cumpliste de sobra con los mínimos.
Se te da muy bien esto y está siendo una gozada verte evolucionar.
¡¡¡Seguimos!!!


![shark](https://user-images.githubusercontent.com/57899051/122940532-d64d7680-d374-11eb-8ecf-ec8861d78af3.jpeg)
