### ISSUE TITLE
[w2-pandas-project] Santi Moreno Pidal

### ISSUE THREAD

**Issue by Santimo89** [Ironhack-Data-Madrid-Mayo-2021/w2-pandas-project#4]
https://github.com/Santimo89/data-cleaning-pandas.git

**Comment by sheriffff** [comment]
- Me gustan en tu readme la presentación y la conclusión, aunque unos bullet points para hacerlo menos parrafaco quizás van bien. No está de más comentar las tecnologías utilizadas, si bien no es obligatorio.
- No veo la estructura solicitada por ningún lado! Solo un notebook con todo? Recuerda, debemos intentar tener archivos de funciones. Propóntelo para los nuevos proyectos.
- Se pedía tener un csv intermedio con el data limpio. Dataset del que tiraría el segundo notebook de análisis. Intentemos hacer esto en el siguiente Santi. Modularizar es ganar.
- Muy poco storytelling. Necesito títulos majos como celdas de jupyter, y alguna línea con conclusiones parciales según avanza el estudio, al menos. Veo muchas gráficas, pero sin comentar. No creo que presentaramos esto en un meeting. El fondo está, démosle forma hombre!

Felicidades por pegarte con pandas para sacar la info necesaria para el estudio.
