### ISSUE TITLE
[w2-pandas-project] Victoria Ruiz

### ISSUE THREAD

**Issue by Vicrgallardon** [Ironhack-Data-Madrid-Mayo-2021/w2-pandas-project#6]
https://github.com/Vicrgallardon/data-cleaning-pandas.git

**Comment by sheriffff** [comment]
Hey Vic. No está mal pero le falta trabajo al proyecto.
- README tiene poca chicha, trabájatelo para hacerlo más atractivo.
- Usas buenos títulos en el jupyter, sigue con ello.
- No has usado apenas los archivos de funciones `.py`, apúntalo en tu lista de TOLEARN y a practicarlo.
- Era un dataset complicado, mucho que limpiar. Aprendemos aquí a priorizar y quedarnos sólo con algunas columnas. Hay que pegarse un poco más con pandas y, una vez que algo funciona, lo pasamos a una función! 
- En algún punto usas Afternoon a pelo, debería ser "Afternoon"
- Visualizaciones majas que permiten responder a tus preguntas más o menos bien.
- Hecho de menos un dataset limpio, y un notebook de analysis. Es bueno separar las cosas.

Has respondido a tus hipótesis, pero le falta atractivo al trabajo y algo de corrección en la limpieza.
